name: Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows]
        goarch: [amd64, arm64]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
        
    - name: Build
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
      run: |
        if [ "${{ matrix.goos }}" = "windows" ]; then
          go build -ldflags="-s -w" -o pgsync-${{ matrix.goos }}-${{ matrix.goarch }}.exe .
          zip pgsync-${{ matrix.goos }}-${{ matrix.goarch }}.zip pgsync-${{ matrix.goos }}-${{ matrix.goarch }}.exe
        else
          go build -ldflags="-s -w" -o pgsync-${{ matrix.goos }}-${{ matrix.goarch }} .
          tar -czvf pgsync-${{ matrix.goos }}-${{ matrix.goarch }}.tar.gz pgsync-${{ matrix.goos }}-${{ matrix.goarch }}
        fi

    - name: Generate Tag
      id: tag
      run: |
        if [[ ${{ github.ref }} == refs/tags/* ]]; then
           echo "tag_name=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        else
           echo "tag_name=latest" >> $GITHUB_OUTPUT
        fi

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.tag.outputs.tag_name }}
        files: |
          *.zip
          *.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
